<?php


include 'config.php';



mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
$db = new mysqli(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
if($db->connect_errno > 0){
    die('Unable to connect to database [' . $db->connect_error . ']');
}



$client_tables = array_merge( $fetchable_tables , $storeable_tables );


?>
<pre>
/**
 *
 *  This file is auto generated by datasync-server/generateClientJS.php
 *  (DB: <?php echo DB_NAME; ?>, DTS: <?php echo gmdate('M d Y H:i:s'); ?> GMT)
 *
 *  Save this file with your client app code as datasync-client/mydb.js 
 *
**/


'use strict';



// Assume jQuery - this function is the hook where you start your app after the DB is ready
$(document).ready(function() {
	
	mydb.thedb.onReady( function() { / * stuff to do when the DB is ready * / } );
	
});




// the JayData Database

$data.Entity.extend("control", {
	id: { type: "int", key: true },
	lastUpdatedDTS: { type: Date }
});
<?php

// for each of the server-side tables we need, create JayData client equalivalents


foreach($client_tables as $t) {
	
	// we make the assumption here that a MySQL table field which has auto increment set
	// is the key field, and we set key: true in the client DB, to force uniquiness restraints
	$auto_inc_extra = ', key: true ';

	// each table in the local DB has it's own local_id also
	
	echo '	
$data.Entity.extend("'.$t.'", { ';
			
	$sql = "SHOW COLUMNS FROM $t";
	$res = $db->query($sql) or die('mysqli error');
	$first = true;
	while ($rec = $res->fetch_assoc()) {
		
		if ($first) {
			$first = false;
		} else {
			echo ',';
		}

		$field = $rec['Field'];
		$type = explode('(', $rec['Type']);
		$type = $type[0];
		switch($type) {
			case 'varchar':		$type = 'text';		break;
			case 'tinyint':		$type = 'bool';		break; // this is the only thing i use tinyints for
			case 'smallint':
			case 'bigint':
			case 'mediumint':	$type = 'int';		break;
			
			// of course there are others !!
			
			default:			$type = $type;		break;
		}
		
		
		$extra1 = ( (stristr($rec['Extra'],'auto_increment'))?$auto_inc_extra:'' );
		
		echo "
	$field: { type: \"$type\" $extra1}";
					
	}
	
	echo '
});
	';


}

// records are defined above, now define the DB "MyDB" 

echo '

$data.EntityContext.extend("MyDB", { ';
$first = true;
foreach($client_tables as $t) {
	if ($first) {
		$first = false;
	} else {
		echo ',';
	}
	echo '
	'.$t.': { type: $data.EntitySet, elementType: '.$t.' }';
}
echo '
});
	';
	
?>



var mydb = {
	
	app_url : '<?php echo "http://". $_SERVER['SERVER_NAME'] . dirname($_SERVER['REQUEST_URI']); ?>',
	app_key : '<?php echo APP_NAME; ?>',
	app_key_suffix : '<?php echo APP_SECRET_KEY; ?>',
	
	thedb : new MyDB("<?php echo APP_NAME; ?>"),
	
	fetch : function (table, where, success, fail) {
		datasync.fetchFromServer (this, table, where, success, fail);
	},
	
	store : function (table, where, success, fail) {
		datasync.store (this, table, where, success, fail);
	}
};




// This structure keeps track of the current DB state
var dataHolder = [
<?php
$first = true;
foreach($client_tables as $t) {
	
	if ($first) {
		$first = false;
	} else {
		echo ',';
	}
			
	echo "
    {
        tableName:  '$t',
        table:      mydb.thedb.$t,
        data:       null,
        state:      'empty'     // empty, downloaded, failed, completed
    }";
}
?>


];

</pre>


