<?php


include 'config.php';



mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
$db = new mysqli(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
if($db->connect_errno > 0){
    die('Unable to connect to database [' . $db->connect_error . ']');
}



$client_tables = array_merge( $fetchable_tables , $storeable_tables );


?>
<pre>
/**
 *
 *  This file is auto generated by datasync-server/generateClientJS.php
 *  (DB: <?php echo DB_NAME; ?>, DTS: <?php echo gmdate('M d Y H:i:s'); ?> GMT)
 *
 *  Save this file with your client app code as datasync-client/mydb.js 
 *
**/

<?php

// for each of the server-side tables we need, create JayData client equalivalents


foreach($client_tables as $t) {
	
	// if the table is a storeable table it means it gets written on the client, and
	// auto_increment fields need to carry over;
	// if the table is only a fetchable table then the "auto" id's come from the server,
	// ie. no need to have the auto_increment behaviour on the client
	if (in_array($t, $storeable_tables)) {
		$auto_inc_extra = ', key: true, computed: true ';
	} else {
		$auto_inc_extra = ', key: true ';
	}

	echo '	
$data.Entity.extend("'.$t.'", {';
			
	$sql = "SHOW COLUMNS FROM $t";
	$res = $db->query($sql) or die('mysqli error');
	$first = true;
	while ($rec = $res->fetch_assoc()) {
		
		if ($first) {
			$first = false;
		} else {
			echo ',';
		}

		$field = $rec['Field'];
		$type = explode('(', $rec['Type']);
		$type = $type[0];
		switch($type) {
			case 'varchar':		$type = 'text';		break;
			case 'tinyint':		$type = 'bool';		break; // this is the only thing i use tinyints for
			case 'smallint':
			case 'bigint':
			case 'mediumint':	$type = 'int';		break;
			
			// of course there are others !!
			
			default:			$type = $type;		break;
		}
		
		
		$extra1 = ( (stristr($rec['Extra'],'auto_increment'))?$auto_inc_extra:'' );
		
		echo "
	$field: { type: \"$type\" $extra1}";
					
	}
	
	echo '
});
	';


}

// records are defined above, now define the DB "MyDB" 

echo '

$data.EntityContext.extend("MyDB", { ';
$first = true;
foreach($client_tables as $t) {
	if ($first) {
		$first = false;
	} else {
		echo ',';
	}
	echo '
	'.$t.': { type: $data.EntitySet, elementType: '.$t.' }';
}
echo '
});
	';
	
?>



var mydb = {
	
	app_url : '<?php echo "http://". $_SERVER['SERVER_NAME'] . dirname($_SERVER['REQUEST_URI']); ?>',
	app_key : '<?php echo APP_NAME; ?>',
	app_key_suffix : '<?php echo APP_SECRET_KEY; ?>',
	
	thedb : new MyDB("<?php echo APP_NAME; ?>"),
	
	fetch : function (table, where, success, fail) {
		datasync.fetch (this, table, where, success, fail);
	},
	
	store : function (table, where, success, fail) {
		datasync.store (this, table, where, success, fail);
	}
}



// assume jQuery - init DB once page is loaded
$(document).ready(function() {
	
	mydb.thedb.onReady( function() { / * stuff to do when the DB is ready * / } );
	
});

</pre>

